# Generated by Django 2.1.2 on 2018-11-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_command_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
