# Generated by Django 2.1.2 on 2018-11-30 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_script_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='name',
            new_name='title',
        ),
    ]
