# Generated by Django 2.1.2 on 2018-12-04 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181130_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='name',
            new_name='title',
        ),
    ]
